twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        const_website_title: "runners-Starter"
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'